### ISSUE TITLE
Add version numbers to `requirements.txt`

### ISSUE THREAD

**Issue by ugultopu** [PonyGE/PonyGE2#86]
Some stuff seems to be broken with the latest versions of dependencies. For example:

    python3 ponyge.py --parameters classification.txt

This has given me the following error:

```
Traceback (most recent call last):
  File "ponyge.py", line 31, in <module>
    mane()
  File "ponyge.py", line 23, in mane
    individuals = params['SEARCH_LOOP']()
  File "PonyGE2/src/algorithm/search_loop.py", line 27, in search_loop
    individuals = evaluate_fitness(individuals)
  File "PonyGE2/src/fitness/evaluation.py", line 76, in evaluate_fitness
    results = eval_or_append(ind, results, pool)
  File "PonyGE2/src/fitness/evaluation.py", line 118, in eval_or_append
    ind.evaluate()
  File "PonyGE2/src/representation/individual.py", line 156, in evaluate
    self.fitness = params['FITNESS_FUNCTION'](self)
  File "PonyGE2/src/fitness/base_ff_classes/base_ff.py", line 35, in __call__
    fitness = self.evaluate(ind, **kwargs)
  File "PonyGE2/src/fitness/supervised_learning/supervised_learning.py", line 99, in evaluate
    return params['ERROR_METRIC'](y, yhat)
  File "PonyGE2/src/utilities/fitness/error_metric.py", line 95, in f1_score
    return sklearn_f1_score(y, yhat)
  File "/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 714, in f1_score
    sample_weight=sample_weight)
  File "/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 828, in fbeta_score
    sample_weight=sample_weight)
  File "/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 1040, in precision_recall_fscore_support
    "choose another average setting." % y_type)
ValueError: Target is multiclass but average='binary'. Please choose another average setting.
```

My guess is that PonyGE2 uses [0.15 version of scikit](http://scikit-learn.org/0.15/modules/generated/sklearn.metrics.f1_score.html), because when I changed this line:

https://github.com/PonyGE/PonyGE2/blob/f667d5efcc2792f7252ec3c090d3e56e2d27756b/src/utilities/fitness/error_metric.py#L95

to:

    return sklearn_f1_score(y, yhat, average = 'weighted')

I didn't get any error.

Could you verify or refute that the cause of the error was using the wrong version of scikit?

**Comment by jmmcd** [comment]
Many thanks. We don't particularly want to rely on 0.15. Setting average='weighted' explicitly instead of relying on the default will work with 0.15 or 0.19. More generally you're probably right that we should have `>=` version numbers in our `requirements.txt`.

(Note: it doesn't happen with sklearn 0.18, which has the same default ('binary') as 0.19, so some other aspect of sklearn warning/error behaviour has also changed between those two versions.)

**Comment by ugultopu** [comment]
@jmmcd Thanks for taking care of this ticket. Actually, AFAIK the best practice is to:
1. Have exact version numbers (`==`) in "requirements.txt".
1. Whenever a new release of the library is wanted to be made, to test stuff (manually or in an automated way) with newer versions of the dependencies and bumping up the versions of the dependencies as required.
