### ISSUE TITLE
program synthesis not "running out of the box"

### ISSUE THREAD

**Issue by mfjoneill** [PonyGE/PonyGE2#95]
Hi all, 

Fyi following the how to run the program synthesis problems from the PonyGE2 Wiki an error is generated, see below...

Best wishes,
Mike.

mike$ python3 ponyge.py --parameters progsys.txt

Start:	 2018-08-15 11:22:14.221973 

Warning: Grammar contains unit production for production rule <predefined>
         Unit productions consume GE codons.
  File "scripts/python_script_evaluation.py", line 76
    print(json.dumps({'exception': exception}), flush=True)
                                                     ^
SyntaxError: invalid syntax
[Errno 32] Broken pipe
Traceback (most recent call last):
  File "ponyge.py", line 31, in <module>
    mane()
  File "ponyge.py", line 23, in mane
    individuals = params['SEARCH_LOOP']()
  File "/Users/mike/Desktop/experiments_temporary_home/PonyGE2-master/src/algorithm/search_loop.py", line 27, in search_loop
    individuals = evaluate_fitness(individuals)
  File "/Users/mike/Desktop/experiments_temporary_home/PonyGE2-master/src/fitness/evaluation.py", line 76, in evaluate_fitness
    results = eval_or_append(ind, results, pool)
  File "/Users/mike/Desktop/experiments_temporary_home/PonyGE2-master/src/fitness/evaluation.py", line 118, in eval_or_append
    ind.evaluate()
  File "/Users/mike/Desktop/experiments_temporary_home/PonyGE2-master/src/representation/individual.py", line 122, in evaluate
    self.fitness = params['FITNESS_FUNCTION'](self)
  File "/Users/mike/Desktop/experiments_temporary_home/PonyGE2-master/src/fitness/base_ff_classes/base_ff.py", line 35, in __call__
    fitness = self.evaluate(ind, **kwargs)
  File "/Users/mike/Desktop/experiments_temporary_home/PonyGE2-master/src/fitness/progsys.py", line 53, in evaluate
    self.eval.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by t-h-e** [comment]
Does that happen every time? Do you have a seed that produces that error?
I can't reproduce the problem, although I have seen it happen with [HeuristicLab.CFGGP](https://github.com/t-h-e/HeuristicLab.CFGGP) as well, but rarely.

**Comment by jmmcd** [comment]
Yes, it is fixed (presumably by #96).

**Comment by nbro** [comment]
@jmmcd Why did you close this issue if you did not accept that pull request? It doesn't make any sense. Issues should be closed when the pull request that solves them is merged (and not before).

**Comment by jmmcd** [comment]
Merged #96. Mike's command-line above works.
